// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppCanvas: typeof import('./src/components/AppCanvas.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppHeaderActions: typeof import('./src/components/AppHeaderActions.vue')['default']
    AppHeaderNav: typeof import('./src/components/AppHeaderNav.vue')['default']
    BaseEmptyContent: typeof import('./src/components/BaseEmptyContent.vue')['default']
    BaseIcon: typeof import('./src/components/BaseIcon.vue')['default']
    CanvasSidebarItem: typeof import('./src/components/CanvasSidebarItem.vue')['default']
    HeaderActions: typeof import('./src/components/HeaderActions.vue')['default']
    HeaderNav: typeof import('./src/components/HeaderNav.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    VanButton: typeof import('vant/es')['Button']
  }
}
